version: '3.8'

services:
  db:
    build: .
    container_name: credential-db
    environment:
      POSTGRES_DB: credential
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: